using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Strings;
using Noggog;
using System.Text;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Aspects;
using Mutagen.Bethesda.Plugins.Cache.Internals.Implementations;
using Mutagen.Bethesda.Plugins.Records;
using System.Text.RegularExpressions;

namespace SynStringMerger;

public class Program
{
    static Program()
    {
        Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
        win1252Encoding = Encoding.GetEncoding(1252);
    }
    static Lazy<Settings> settings = null!;
    static Settings Settings => settings!.Value;
    static Encoding UnicodeEncoding = Encoding.Unicode;
    static Encoding utf8Encoding = Encoding.UTF8;
    static Encoding win1252Encoding = null!;
    static Regex isFullEnglishRegex = new Regex(@"^[\x00-\xff]+$", RegexOptions.Compiled);
    static Regex isFullUpperCamelCase = new Regex(@"^([A-Z]+[a-z0-9]+)+$", RegexOptions.Compiled);

    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "translator.json", out settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "SimpleTranslator.esp")
            .Run(args);
    }

    public static string EncodingConvert(string str)
    {
        var bytes = UnicodeEncoding.GetBytes(str);
        Console.WriteLine(bytes);
        return win1252Encoding.GetString(bytes);
    }

    public static void Patch<TCache, TTarget>(
        ImmutableLoadOrderLinkCache<ISkyrimMod, ISkyrimModGetter> cache,
        ImmutableLoadOrderLinkCache<ISkyrimMod, ISkyrimModGetter> highPriorityCache,
        IEnumerable<TCache> sourceModEntities,
        IGroup<TTarget> patchedModsEntities,
        string keyWord,
        Action<TTarget, TCache>? action = null)
        where TCache : class, IMajorRecordGetter, ITranslatedNamedGetter
        where TTarget : class, IMajorRecordInternal, ITranslatedNamed, TCache
    {
        int i = 0;
        // 遍历 FormList
        foreach (var translating in Settings.PatchAllEntity ? sourceModEntities : patchedModsEntities)
        {
            // Get the name of the entity
            var resolveResult = highPriorityCache.TryResolve<TCache>(translating.FormKey, out var nameSource, ResolveTarget.Winner);
            if (!resolveResult)
            {
                resolveResult = cache.TryResolve<TCache>(translating.FormKey, out nameSource, Settings.ResolveFromOrigin ? ResolveTarget.Origin : ResolveTarget.Winner);
            }
            if (Settings.Verbose)
            {
                Console.Write($"[{keyWord}] EditorId:[{translating.EditorID}], FormId:[{translating.FormKey.ID}] ");
            }
            if (!resolveResult || nameSource == null)
            {
                Console.WriteLine($"Resolving {translating.FormKey} from {(Settings.ResolveFromOrigin ? "Origin" : "Winner")} Failed");
                continue;
            }

            // Skip if the name no need to be translated
            if (Settings.SkipSameString && nameSource.Name?.String != null && translating.Name?.String != null
                && nameSource.Name.String.Equals(translating.Name.String))
            {
                // 全是中文或者是大驼峰
                if (!(Settings.DontSkipAllEnglish && isFullEnglishRegex.IsMatch(nameSource.Name.String))
                    || isFullUpperCamelCase.IsMatch(nameSource.Name.String))
                {
                    if (Settings.Verbose)
                    {
                        Console.WriteLine($"{nameSource.Name.String} Skipped");
                    }
                    continue;
                }
            }
            var target = patchedModsEntities.GetOrAddAsOverride(translating);
            if (nameSource.Name?.String != null && target?.Name?.String != null)
            {
                var translatedName = Settings.CustomDictionary.ContainsKey(nameSource.Name.String)
                    ? Settings.CustomDictionary[nameSource.Name.String] : nameSource.Name.String;
                if (Settings.Verbose && string.Equals(target.Name.String, translatedName))
                {
                    Console.WriteLine($"{nameSource.Name.String} Skipped");
                    continue;
                }
                if (Settings.Verbose)
                {
                    Console.WriteLine($"{translating.Name} ==> {translatedName}");
                }
                target.Name = translatedName;
                action?.Invoke(target, nameSource);
                i++;
            }
            else if (Settings.Verbose)
            {
                Console.WriteLine("Something is null");
            }
        }
        Console.WriteLine($"Patched {i}");
    }

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        if (!Settings.LogPath.IsNullOrEmpty())
        {
            FileStream fileStream = new FileStream(Settings.LogPath, FileMode.Create);
            var streamWriter = new StreamWriter(fileStream, utf8Encoding);
            streamWriter.AutoFlush = true;
            Console.SetOut(streamWriter);
        }
        var highPriorityCache = state.LoadOrder.ListedOrder
            .Where(x => Settings.HighPriorityMods.Contains(x.ModKey))
            .OrderBy(x => Settings.HighPriorityMods.IndexOf(x.ModKey))
            .ToImmutableLinkCache();
        var cache = state.LoadOrder.ListedOrder
            .SkipLast(1)
            .Where(x =>
            {
                if (x.ModKey.Equals(state.PatchMod.ModKey))
                {
                    return false;
                }
                if (Settings.IgnorePatchMods && x.ModKey.Name.ContainsInsensitive("Patch") && !Settings.IncludedPatchMods.Contains(x.ModKey))
                {
                    return false;
                }
                return Settings.WhiteListMode ? Settings.WhiteList.Contains(x.ModKey) : !Settings.BlackList.Contains(x.ModKey);
            })
            .ToImmutableLinkCache();

        if (Settings.Verbose)
        {
            Console.WriteLine();
            Console.WriteLine("===========================================");
            Console.WriteLine("========== Caches Priority Order ==========");
            Console.WriteLine("===========================================");
            Console.WriteLine($"Reference name from lowest priority: {Settings.ResolveFromOrigin}");
            cache.PriorityOrder.ForEach(x => Console.WriteLine($"{x.ModKey}"));
        }

        if (Settings.Npc)
        {
            Console.WriteLine();
            Console.WriteLine("==================================");
            Console.WriteLine("========== Patching NPC ==========");
            Console.WriteLine("==================================");

            Patch(cache, highPriorityCache, state.LoadOrder.PriorityOrder.Npc().WinningOverrides(), state.PatchMod.Npcs, "NPC", (target, cache) =>
            {
                if (cache.ShortName != null)
                {
                    target.ShortName = cache.ShortName.String;
                }
            });
        }

        if (Settings.Weapon)
        {
            Console.WriteLine();
            Console.WriteLine("=====================================");
            Console.WriteLine("========== Patching Weapon ==========");
            Console.WriteLine("=====================================");
            Patch(cache, highPriorityCache, state.LoadOrder.PriorityOrder.Weapon().WinningOverrides(), state.PatchMod.Weapons, "Weapon");
        }

        if (Settings.Armor)
        {
            Console.WriteLine();
            Console.WriteLine("====================================");
            Console.WriteLine("========== Patching Armor ==========");
            Console.WriteLine("====================================");
            Patch(cache, highPriorityCache, state.LoadOrder.PriorityOrder.Armor().WinningOverrides(), state.PatchMod.Armors, "Armor", (target, cache) =>
            {
                target.Description?.Set(Language.English, cache.Description?.String);
            });
        }

        if (Settings.Item)
        {
            Console.WriteLine();
            Console.WriteLine("===================================");
            Console.WriteLine("========== Patching Item ==========");
            Console.WriteLine("===================================");
            Patch(cache, highPriorityCache, state.LoadOrder.PriorityOrder.MiscItem().WinningOverrides(), state.PatchMod.MiscItems, "Item");
            Patch(cache, highPriorityCache, state.LoadOrder.PriorityOrder.SoulGem().WinningOverrides(), state.PatchMod.SoulGems, "SoulGems");
        }

        if (Settings.WorldSpace)
        {
            Console.WriteLine();
            Console.WriteLine("==============================================");
            Console.WriteLine("========== Patching WorldSpace/Cell ==========");
            Console.WriteLine("==============================================");
            Patch(cache, highPriorityCache, state.LoadOrder.PriorityOrder.Worldspace().WinningOverrides(), state.PatchMod.Worldspaces, "WorldSpace");
            IEnumerable<ICellGetter> cellGetters = state.LoadOrder.PriorityOrder.Cell().WinningOverrides();
            var cellSubBlocks = state.PatchMod.Cells.SelectMany(x => x.SubBlocks);
            var cells = cellSubBlocks.SelectMany(x => x.Cells);
        }

        if (Settings.Perk)
        {
            Console.WriteLine();
            Console.WriteLine("===================================");
            Console.WriteLine("========== Patching Perk ==========");
            Console.WriteLine("===================================");
            Patch(cache, highPriorityCache, state.LoadOrder.PriorityOrder.Perk().WinningOverrides(), state.PatchMod.Perks, "Perk", (target, cache) =>
            {
                target.Description.Set(cache.Description.TargetLanguage, cache.Description.String);
            });
            var test = state.PatchMod.TryGetTopLevelGroup<Cell>();
        }

        if (Settings.Books)
        {
            Console.WriteLine();
            Console.WriteLine("====================================");
            Console.WriteLine("========== Patching Books ==========");
            Console.WriteLine("====================================");
            Patch(cache, highPriorityCache, state.LoadOrder.PriorityOrder.Book().WinningOverrides(), state.PatchMod.Books, "Books", (target, cache) =>
            {
                target.BookText.Set(cache.BookText.TargetLanguage, cache.BookText.String);
            });
        }
    }
}
